"""add key_points and decisions to summaries

Revision ID: 9b5f1554ca6b
Revises: cd814acd128f
Create Date: 2026-09-12 14:34:16.456644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5f1554ca6b'
down_revision: Union[str, None] = 'cd814acd128f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('key_points', sa.JSON(), nullable=True))
    op.add_column('summaries', sa.Column('decisions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'decisions')
    op.drop_column('summaries', 'key_points')
    # ### end Alembic commands ###
