"""add completed to action items

Revision ID: b0b0facd06ff
Revises: 9b5f1554ca6b
Create Date: 2026-09-12 21:17:44.882932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b0facd06ff'
down_revision: Union[str, None] = '9b5f1554ca6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "action_items",
        sa.Column("completed", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("action_items", "completed")
    # ### end Alembic commands ###
